// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient
{
    using Microsoft.Rest;
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// DrawImageOperations operations.
    /// </summary>
    public partial interface IDrawImageOperations
    {
        /// <param name='name'>
        /// </param>
        /// <param name='format'>
        /// </param>
        /// <param name='width'>
        /// </param>
        /// <param name='height'>
        /// </param>
        /// <param name='fontSize'>
        /// </param>
        /// <param name='foreground'>
        /// </param>
        /// <param name='background'>
        /// </param>
        /// <param name='format1'>
        /// Specifies response output format
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<string>> GetWithHttpMessagesAsync(string name, string format = default(string), int? width = default(int?), int? height = default(int?), int? fontSize = default(int?), string foreground = default(string), string background = default(string), string format1 = "json", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='name'>
        /// </param>
        /// <param name='format'>
        /// </param>
        /// <param name='width'>
        /// </param>
        /// <param name='height'>
        /// </param>
        /// <param name='fontSize'>
        /// </param>
        /// <param name='foreground'>
        /// </param>
        /// <param name='background'>
        /// </param>
        /// <param name='format1'>
        /// Specifies response output format
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<string>> CreateWithHttpMessagesAsync(string name, string format = default(string), int? width = default(int?), int? height = default(int?), int? fontSize = default(int?), string foreground = default(string), string background = default(string), string format1 = "json", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='name'>
        /// </param>
        /// <param name='format'>
        /// </param>
        /// <param name='width'>
        /// </param>
        /// <param name='height'>
        /// </param>
        /// <param name='fontSize'>
        /// </param>
        /// <param name='foreground'>
        /// </param>
        /// <param name='background'>
        /// </param>
        /// <param name='format1'>
        /// Specifies response output format
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<string>> PostWithHttpMessagesAsync(string name, string format = default(string), int? width = default(int?), int? height = default(int?), int? fontSize = default(int?), string foreground = default(string), string background = default(string), string format1 = "json", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <param name='name'>
        /// </param>
        /// <param name='format'>
        /// </param>
        /// <param name='width'>
        /// </param>
        /// <param name='height'>
        /// </param>
        /// <param name='fontSize'>
        /// </param>
        /// <param name='foreground'>
        /// </param>
        /// <param name='background'>
        /// </param>
        /// <param name='format1'>
        /// Specifies response output format
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        Task<HttpOperationResponse<string>> DeleteWithHttpMessagesAsync(string name, string format = default(string), int? width = default(int?), int? height = default(int?), int? fontSize = default(int?), string foreground = default(string), string background = default(string), string format1 = "json", Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
