// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface ITest : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IThrowHttpErrorOperations.
        /// </summary>
        IThrowHttpErrorOperations ThrowHttpError { get; }

        /// <summary>
        /// Gets the IThrow404Operations.
        /// </summary>
        IThrow404Operations Throw404 { get; }

        /// <summary>
        /// Gets the IThrowCustom400Operations.
        /// </summary>
        IThrowCustom400Operations ThrowCustom400 { get; }

        /// <summary>
        /// Gets the IThrowTypeOperations.
        /// </summary>
        IThrowTypeOperations ThrowType { get; }

        /// <summary>
        /// Gets the IThrowValidationOperations.
        /// </summary>
        IThrowValidationOperations ThrowValidation { get; }

        /// <summary>
        /// Gets the IThrowBusinessError.
        /// </summary>
        IThrowBusinessError ThrowBusinessError { get; }

        /// <summary>
        /// Gets the IImageAsStreamOperations.
        /// </summary>
        IImageAsStreamOperations ImageAsStream { get; }

        /// <summary>
        /// Gets the IImageAsBytesOperations.
        /// </summary>
        IImageAsBytesOperations ImageAsBytes { get; }

        /// <summary>
        /// Gets the IImageAsCustomResultOperations.
        /// </summary>
        IImageAsCustomResultOperations ImageAsCustomResult { get; }

        /// <summary>
        /// Gets the IImageWriteToResponseOperations.
        /// </summary>
        IImageWriteToResponseOperations ImageWriteToResponse { get; }

        /// <summary>
        /// Gets the IImageAsFileOperations.
        /// </summary>
        IImageAsFileOperations ImageAsFile { get; }

        /// <summary>
        /// Gets the IImageAsRedirectOperations.
        /// </summary>
        IImageAsRedirectOperations ImageAsRedirect { get; }

        /// <summary>
        /// Gets the IDrawImageOperations.
        /// </summary>
        IDrawImageOperations DrawImage { get; }

        /// <summary>
        /// Gets the IMetadataTestOperations.
        /// </summary>
        IMetadataTestOperations MetadataTest { get; }

        /// <summary>
        /// Gets the IMetadataTestArrayOperations.
        /// </summary>
        IMetadataTestArrayOperations MetadataTestArray { get; }

        /// <summary>
        /// Gets the IGetExample.
        /// </summary>
        IGetExample GetExample { get; }

        /// <summary>
        /// Gets the IGetRandomIdsOperations.
        /// </summary>
        IGetRandomIdsOperations GetRandomIds { get; }

        /// <summary>
        /// Gets the ITextFileTestOperations.
        /// </summary>
        ITextFileTestOperations TextFileTest { get; }

        /// <summary>
        /// Gets the IHelloOperations.
        /// </summary>
        IHelloOperations Hello { get; }

        /// <summary>
        /// Gets the IHelloAllTypesOperations.
        /// </summary>
        IHelloAllTypesOperations HelloAllTypes { get; }

        /// <summary>
        /// Gets the IHelloWithRouteOperations.
        /// </summary>
        IHelloWithRouteOperations HelloWithRoute { get; }

        /// <summary>
        /// Gets the IHelloTypesOperations.
        /// </summary>
        IHelloTypesOperations HelloTypes { get; }

        /// <summary>
        /// Gets the IHelloZipOperations.
        /// </summary>
        IHelloZipOperations HelloZip { get; }

        /// <summary>
        /// Gets the IPing.
        /// </summary>
        IPing Ping { get; }

        /// <summary>
        /// Gets the IRequiresRole.
        /// </summary>
        IRequiresRole RequiresRole { get; }

        /// <summary>
        /// Gets the IReturnStringOperations.
        /// </summary>
        IReturnStringOperations ReturnString { get; }

        /// <summary>
        /// Gets the IReturnBytesOperations.
        /// </summary>
        IReturnBytesOperations ReturnBytes { get; }

        /// <summary>
        /// Gets the IReturnStreamOperations.
        /// </summary>
        IReturnStreamOperations ReturnStream { get; }

        /// <summary>
        /// Gets the IGetRequest1.
        /// </summary>
        IGetRequest1 GetRequest1 { get; }

        /// <summary>
        /// Gets the IGetRequest2.
        /// </summary>
        IGetRequest2 GetRequest2 { get; }

        /// <summary>
        /// Gets the ISendRestGetOperations.
        /// </summary>
        ISendRestGetOperations SendRestGet { get; }

        /// <summary>
        /// Gets the IGetSession.
        /// </summary>
        IGetSession GetSession { get; }

        /// <summary>
        /// Gets the IUpdateSessionOperations.
        /// </summary>
        IUpdateSessionOperations UpdateSession { get; }

        /// <summary>
        /// Gets the ITestAuth.
        /// </summary>
        ITestAuth TestAuth { get; }

        /// <summary>
        /// Gets the ITestVoidResponse.
        /// </summary>
        ITestVoidResponse TestVoidResponse { get; }

        /// <summary>
        /// Gets the ITestNullResponse.
        /// </summary>
        ITestNullResponse TestNullResponse { get; }

        /// <summary>
        /// Gets the IWaitOperations.
        /// </summary>
        IWaitOperations Wait { get; }

        /// <summary>
        /// Gets the IEchoTypesOperations.
        /// </summary>
        IEchoTypesOperations EchoTypes { get; }

        /// <summary>
        /// Gets the IEchoCollectionsOperations.
        /// </summary>
        IEchoCollectionsOperations EchoCollections { get; }

        /// <summary>
        /// Gets the IQueryRockstarsOperations.
        /// </summary>
        IQueryRockstarsOperations QueryRockstars { get; }

        /// <summary>
        /// Gets the IAuthenticateOperations.
        /// </summary>
        IAuthenticateOperations Authenticate { get; }

        /// <summary>
        /// Gets the IAssignRolesOperations.
        /// </summary>
        IAssignRolesOperations AssignRoles { get; }

        /// <summary>
        /// Gets the IUnAssignRolesOperations.
        /// </summary>
        IUnAssignRolesOperations UnAssignRoles { get; }

    }
}
