// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for ReturnBytesOperations.
    /// </summary>
    public static partial class ReturnBytesOperationsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static IList<byte[]> Get(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json")
            {
                return operations.GetAsync(data, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<byte[]>> GetAsync(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(data, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static IList<byte[]> Create(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json")
            {
                return operations.CreateAsync(data, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<byte[]>> CreateAsync(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.CreateWithHttpMessagesAsync(data, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static IList<byte[]> Post(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json")
            {
                return operations.PostAsync(data, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<byte[]>> PostAsync(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(data, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            public static IList<byte[]> Delete(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json")
            {
                return operations.DeleteAsync(data, format).GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='data'>
            /// </param>
            /// <param name='format'>
            /// Specifies response output format
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<byte[]>> DeleteAsync(this IReturnBytesOperations operations, IList<byte[]> data = default(IList<byte[]>), string format = "json", CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeleteWithHttpMessagesAsync(data, format, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
