// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// AllCollectionTypes
    /// </summary>
    public partial class AllCollectionTypes
    {
        /// <summary>
        /// Initializes a new instance of the AllCollectionTypes class.
        /// </summary>
        public AllCollectionTypes() { }

        /// <summary>
        /// Initializes a new instance of the AllCollectionTypes class.
        /// </summary>
        public AllCollectionTypes(IList<int?> intArray = default(IList<int?>), IList<int?> intList = default(IList<int?>), IList<string> stringArray = default(IList<string>), IList<string> stringList = default(IList<string>), IList<Poco> pocoArray = default(IList<Poco>), IList<Poco> pocoList = default(IList<Poco>), object pocoLookup = default(object), object pocoLookupMap = default(object))
        {
            IntArray = intArray;
            IntList = intList;
            StringArray = stringArray;
            StringList = stringList;
            PocoArray = pocoArray;
            PocoList = pocoList;
            PocoLookup = pocoLookup;
            PocoLookupMap = pocoLookupMap;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IntArray")]
        public IList<int?> IntArray { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IntList")]
        public IList<int?> IntList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StringArray")]
        public IList<string> StringArray { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StringList")]
        public IList<string> StringList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PocoArray")]
        public IList<Poco> PocoArray { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PocoList")]
        public IList<Poco> PocoList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PocoLookup")]
        public object PocoLookup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PocoLookupMap")]
        public object PocoLookupMap { get; set; }

    }
}
