// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// GetRandomIds
    /// </summary>
    public partial class GetRandomIds
    {
        /// <summary>
        /// Initializes a new instance of the GetRandomIds class.
        /// </summary>
        public GetRandomIds() { }

        /// <summary>
        /// Initializes a new instance of the GetRandomIds class.
        /// </summary>
        public GetRandomIds(int? take = default(int?))
        {
            Take = take;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Take")]
        public int? Take { get; set; }

    }
}
