// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// GetSessionResponse
    /// </summary>
    public partial class GetSessionResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetSessionResponse class.
        /// </summary>
        public GetSessionResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetSessionResponse class.
        /// </summary>
        public GetSessionResponse(CustomUserSession result = default(CustomUserSession), UnAuthInfo unAuthInfo = default(UnAuthInfo), ResponseStatus responseStatus = default(ResponseStatus))
        {
            Result = result;
            UnAuthInfo = unAuthInfo;
            ResponseStatus = responseStatus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Result")]
        public CustomUserSession Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnAuthInfo")]
        public UnAuthInfo UnAuthInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseStatus")]
        public ResponseStatus ResponseStatus { get; set; }

    }
}
