// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// HelloWithRoute
    /// </summary>
    public partial class HelloWithRoute
    {
        /// <summary>
        /// Initializes a new instance of the HelloWithRoute class.
        /// </summary>
        public HelloWithRoute() { }

        /// <summary>
        /// Initializes a new instance of the HelloWithRoute class.
        /// </summary>
        public HelloWithRoute(string name = default(string))
        {
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
