// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// HelloAllTypes
    /// </summary>
    public partial class HelloAllTypes
    {
        /// <summary>
        /// Initializes a new instance of the HelloAllTypes class.
        /// </summary>
        public HelloAllTypes() { }

        /// <summary>
        /// Initializes a new instance of the HelloAllTypes class.
        /// </summary>
        public HelloAllTypes(string name = default(string), AllTypes allTypes = default(AllTypes), AllCollectionTypes allCollectionTypes = default(AllCollectionTypes))
        {
            Name = name;
            AllTypes = allTypes;
            AllCollectionTypes = allCollectionTypes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllTypes")]
        public AllTypes AllTypes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AllCollectionTypes")]
        public AllCollectionTypes AllCollectionTypes { get; set; }

    }
}
