// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Hello
    /// </summary>
    public partial class Hello
    {
        /// <summary>
        /// Initializes a new instance of the Hello class.
        /// </summary>
        public Hello() { }

        /// <summary>
        /// Initializes a new instance of the Hello class.
        /// </summary>
        public Hello(string name = default(string), string title = default(string))
        {
            Name = name;
            Title = title;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

    }
}
