// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// IdentityTestRequest1
    /// </summary>
    public partial class IdentityTestRequest1
    {
        /// <summary>
        /// Initializes a new instance of the IdentityTestRequest1 class.
        /// </summary>
        public IdentityTestRequest1() { }

        /// <summary>
        /// Initializes a new instance of the IdentityTestRequest1 class.
        /// </summary>
        public IdentityTestRequest1(object personId = default(object))
        {
            PersonId = personId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonId")]
        public object PersonId { get; set; }

    }
}
