// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ImageAsFile
    /// </summary>
    public partial class ImageAsFile
    {
        /// <summary>
        /// Initializes a new instance of the ImageAsFile class.
        /// </summary>
        public ImageAsFile() { }

        /// <summary>
        /// Initializes a new instance of the ImageAsFile class.
        /// </summary>
        public ImageAsFile(string format = default(string))
        {
            Format = format;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Format")]
        public string Format { get; set; }

    }
}
