// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ImageAsBytes
    /// </summary>
    public partial class ImageAsBytes
    {
        /// <summary>
        /// Initializes a new instance of the ImageAsBytes class.
        /// </summary>
        public ImageAsBytes() { }

        /// <summary>
        /// Initializes a new instance of the ImageAsBytes class.
        /// </summary>
        public ImageAsBytes(string format = default(string))
        {
            Format = format;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Format")]
        public string Format { get; set; }

    }
}
