// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// MenuExample
    /// </summary>
    public partial class MenuExample
    {
        /// <summary>
        /// Initializes a new instance of the MenuExample class.
        /// </summary>
        public MenuExample() { }

        /// <summary>
        /// Initializes a new instance of the MenuExample class.
        /// </summary>
        public MenuExample(MenuItemExample menuItemExample1 = default(MenuItemExample))
        {
            MenuItemExample1 = menuItemExample1;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MenuItemExample1")]
        public MenuItemExample MenuItemExample1 { get; set; }

    }
}
