// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// MenuItemExampleItem
    /// </summary>
    public partial class MenuItemExampleItem
    {
        /// <summary>
        /// Initializes a new instance of the MenuItemExampleItem class.
        /// </summary>
        public MenuItemExampleItem() { }

        /// <summary>
        /// Initializes a new instance of the MenuItemExampleItem class.
        /// </summary>
        public MenuItemExampleItem(string name1 = default(string))
        {
            Name1 = name1;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name1")]
        public string Name1 { get; set; }

    }
}
