// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// MetadataTest
    /// </summary>
    public partial class MetadataTest
    {
        /// <summary>
        /// Initializes a new instance of the MetadataTest class.
        /// </summary>
        public MetadataTest() { }

        /// <summary>
        /// Initializes a new instance of the MetadataTest class.
        /// </summary>
        public MetadataTest(int? id = default(int?))
        {
            Id = id;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

    }
}
