// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// MetadataTestNestedChild
    /// </summary>
    public partial class MetadataTestNestedChild
    {
        /// <summary>
        /// Initializes a new instance of the MetadataTestNestedChild class.
        /// </summary>
        public MetadataTestNestedChild() { }

        /// <summary>
        /// Initializes a new instance of the MetadataTestNestedChild class.
        /// </summary>
        public MetadataTestNestedChild(string name = default(string))
        {
            Name = name;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

    }
}
