// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// MetadataTestChild
    /// </summary>
    public partial class MetadataTestChild
    {
        /// <summary>
        /// Initializes a new instance of the MetadataTestChild class.
        /// </summary>
        public MetadataTestChild() { }

        /// <summary>
        /// Initializes a new instance of the MetadataTestChild class.
        /// </summary>
        public MetadataTestChild(string name = default(string), IList<MetadataTestNestedChild> results = default(IList<MetadataTestNestedChild>))
        {
            Name = name;
            Results = results;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Results")]
        public IList<MetadataTestNestedChild> Results { get; set; }

    }
}
