// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// MetadataTestResponse
    /// </summary>
    public partial class MetadataTestResponse
    {
        /// <summary>
        /// Initializes a new instance of the MetadataTestResponse class.
        /// </summary>
        public MetadataTestResponse() { }

        /// <summary>
        /// Initializes a new instance of the MetadataTestResponse class.
        /// </summary>
        public MetadataTestResponse(int? id = default(int?), IList<MetadataTestChild> results = default(IList<MetadataTestChild>))
        {
            Id = id;
            Results = results;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Results")]
        public IList<MetadataTestChild> Results { get; set; }

    }
}
