// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// QueryRockstars
    /// </summary>
    public partial class QueryRockstars
    {
        /// <summary>
        /// Initializes a new instance of the QueryRockstars class.
        /// </summary>
        public QueryRockstars() { }

        /// <summary>
        /// Initializes a new instance of the QueryRockstars class.
        /// </summary>
        public QueryRockstars(int? skip = default(int?), int? take = default(int?), string orderBy = default(string), string orderByDesc = default(string), string include = default(string), string fields = default(string), object meta = default(object))
        {
            Skip = skip;
            Take = take;
            OrderBy = orderBy;
            OrderByDesc = orderByDesc;
            Include = include;
            Fields = fields;
            Meta = meta;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Skip")]
        public int? Skip { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Take")]
        public int? Take { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderBy")]
        public string OrderBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OrderByDesc")]
        public string OrderByDesc { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Include")]
        public string Include { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Fields")]
        public string Fields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Meta")]
        public object Meta { get; set; }

    }
}
