// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// QueryResponse&lt;Rockstar&gt;
    /// </summary>
    public partial class QueryResponseRockstar
    {
        /// <summary>
        /// Initializes a new instance of the QueryResponseRockstar class.
        /// </summary>
        public QueryResponseRockstar() { }

        /// <summary>
        /// Initializes a new instance of the QueryResponseRockstar class.
        /// </summary>
        public QueryResponseRockstar(int? offset = default(int?), int? total = default(int?), IList<Rockstar> results = default(IList<Rockstar>), object meta = default(object), ResponseStatus responseStatus = default(ResponseStatus))
        {
            Offset = offset;
            Total = total;
            Results = results;
            Meta = meta;
            ResponseStatus = responseStatus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Offset")]
        public int? Offset { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Total")]
        public int? Total { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Results")]
        public IList<Rockstar> Results { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Meta")]
        public object Meta { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseStatus")]
        public ResponseStatus ResponseStatus { get; set; }

    }
}
