// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ResponseError
    /// </summary>
    public partial class ResponseError
    {
        /// <summary>
        /// Initializes a new instance of the ResponseError class.
        /// </summary>
        public ResponseError() { }

        /// <summary>
        /// Initializes a new instance of the ResponseError class.
        /// </summary>
        public ResponseError(string errorCode = default(string), string fieldName = default(string), string message = default(string), object meta = default(object))
        {
            ErrorCode = errorCode;
            FieldName = fieldName;
            Message = message;
            Meta = meta;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorCode")]
        public string ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FieldName")]
        public string FieldName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Meta")]
        public object Meta { get; set; }

    }
}
