// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ReturnString
    /// </summary>
    public partial class ReturnString
    {
        /// <summary>
        /// Initializes a new instance of the ReturnString class.
        /// </summary>
        public ReturnString() { }

        /// <summary>
        /// Initializes a new instance of the ReturnString class.
        /// </summary>
        public ReturnString(string data = default(string))
        {
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public string Data { get; set; }

    }
}
