// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// ReturnBytes
    /// </summary>
    public partial class ReturnBytes
    {
        /// <summary>
        /// Initializes a new instance of the ReturnBytes class.
        /// </summary>
        public ReturnBytes() { }

        /// <summary>
        /// Initializes a new instance of the ReturnBytes class.
        /// </summary>
        public ReturnBytes(IList<byte[]> data = default(IList<byte[]>))
        {
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public IList<byte[]> Data { get; set; }

    }
}
