// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ReturnStream
    /// </summary>
    public partial class ReturnStream
    {
        /// <summary>
        /// Initializes a new instance of the ReturnStream class.
        /// </summary>
        public ReturnStream() { }

        /// <summary>
        /// Initializes a new instance of the ReturnStream class.
        /// </summary>
        public ReturnStream(byte[] data = default(byte[]))
        {
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public byte[] Data { get; set; }

    }
}
