// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Rockstar
    /// </summary>
    public partial class Rockstar
    {
        /// <summary>
        /// Initializes a new instance of the Rockstar class.
        /// </summary>
        public Rockstar() { }

        /// <summary>
        /// Initializes a new instance of the Rockstar class.
        /// </summary>
        public Rockstar(int? id = default(int?), string firstName = default(string), string lastName = default(string), int? age = default(int?))
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
            Age = age;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Age")]
        public int? Age { get; set; }

    }
}
