// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// SendVerbResponse
    /// </summary>
    public partial class SendVerbResponse
    {
        /// <summary>
        /// Initializes a new instance of the SendVerbResponse class.
        /// </summary>
        public SendVerbResponse() { }

        /// <summary>
        /// Initializes a new instance of the SendVerbResponse class.
        /// </summary>
        public SendVerbResponse(int? id = default(int?), string pathInfo = default(string), string requestMethod = default(string))
        {
            Id = id;
            PathInfo = pathInfo;
            RequestMethod = requestMethod;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PathInfo")]
        public string PathInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestMethod")]
        public string RequestMethod { get; set; }

    }
}
