// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// TestAuthResponse
    /// </summary>
    public partial class TestAuthResponse
    {
        /// <summary>
        /// Initializes a new instance of the TestAuthResponse class.
        /// </summary>
        public TestAuthResponse() { }

        /// <summary>
        /// Initializes a new instance of the TestAuthResponse class.
        /// </summary>
        public TestAuthResponse(string userId = default(string), string sessionId = default(string), string userName = default(string), string displayName = default(string), ResponseStatus responseStatus = default(ResponseStatus))
        {
            UserId = userId;
            SessionId = sessionId;
            UserName = userName;
            DisplayName = displayName;
            ResponseStatus = responseStatus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SessionId")]
        public string SessionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisplayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseStatus")]
        public ResponseStatus ResponseStatus { get; set; }

    }
}
