// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// TextFileTest
    /// </summary>
    public partial class TextFileTest
    {
        /// <summary>
        /// Initializes a new instance of the TextFileTest class.
        /// </summary>
        public TextFileTest() { }

        /// <summary>
        /// Initializes a new instance of the TextFileTest class.
        /// </summary>
        public TextFileTest(bool? asAttachment = default(bool?))
        {
            AsAttachment = asAttachment;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AsAttachment")]
        public bool? AsAttachment { get; set; }

    }
}
