// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ThrowTypeResponse
    /// </summary>
    public partial class ThrowTypeResponse
    {
        /// <summary>
        /// Initializes a new instance of the ThrowTypeResponse class.
        /// </summary>
        public ThrowTypeResponse() { }

        /// <summary>
        /// Initializes a new instance of the ThrowTypeResponse class.
        /// </summary>
        public ThrowTypeResponse(ResponseStatus responseStatus = default(ResponseStatus))
        {
            ResponseStatus = responseStatus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseStatus")]
        public ResponseStatus ResponseStatus { get; set; }

    }
}
