// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Throw404
    /// </summary>
    public partial class Throw404
    {
        /// <summary>
        /// Initializes a new instance of the Throw404 class.
        /// </summary>
        public Throw404() { }

        /// <summary>
        /// Initializes a new instance of the Throw404 class.
        /// </summary>
        public Throw404(string message = default(string))
        {
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
