// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ThrowValidation
    /// </summary>
    public partial class ThrowValidation
    {
        /// <summary>
        /// Initializes a new instance of the ThrowValidation class.
        /// </summary>
        public ThrowValidation() { }

        /// <summary>
        /// Initializes a new instance of the ThrowValidation class.
        /// </summary>
        public ThrowValidation(int? age = default(int?), string required = default(string), string email = default(string))
        {
            Age = age;
            Required = required;
            Email = email;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Age")]
        public int? Age { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Required")]
        public string Required { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

    }
}
