// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ThrowType
    /// </summary>
    public partial class ThrowType
    {
        /// <summary>
        /// Initializes a new instance of the ThrowType class.
        /// </summary>
        public ThrowType() { }

        /// <summary>
        /// Initializes a new instance of the ThrowType class.
        /// </summary>
        public ThrowType(string type = default(string), string message = default(string))
        {
            Type = type;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
