// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ThrowHttpError
    /// </summary>
    public partial class ThrowHttpError
    {
        /// <summary>
        /// Initializes a new instance of the ThrowHttpError class.
        /// </summary>
        public ThrowHttpError() { }

        /// <summary>
        /// Initializes a new instance of the ThrowHttpError class.
        /// </summary>
        public ThrowHttpError(int? status = default(int?), string message = default(string))
        {
            Status = status;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public int? Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

    }
}
