// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// ThrowValidationResponse
    /// </summary>
    public partial class ThrowValidationResponse
    {
        /// <summary>
        /// Initializes a new instance of the ThrowValidationResponse class.
        /// </summary>
        public ThrowValidationResponse() { }

        /// <summary>
        /// Initializes a new instance of the ThrowValidationResponse class.
        /// </summary>
        public ThrowValidationResponse(int? age = default(int?), string required = default(string), string email = default(string), ResponseStatus responseStatus = default(ResponseStatus))
        {
            Age = age;
            Required = required;
            Email = email;
            ResponseStatus = responseStatus;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Age")]
        public int? Age { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Required")]
        public string Required { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponseStatus")]
        public ResponseStatus ResponseStatus { get; set; }

    }
}
