// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace TestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Wait
    /// </summary>
    public partial class Wait
    {
        /// <summary>
        /// Initializes a new instance of the Wait class.
        /// </summary>
        public Wait() { }

        /// <summary>
        /// Initializes a new instance of the Wait class.
        /// </summary>
        public Wait(int? forMs = default(int?))
        {
            ForMs = forMs;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForMs")]
        public int? ForMs { get; set; }

    }
}
